#! /usr/bin/env bash

# Directory config. Where the template file and the summary files go
TEMPLATE=~/Projects/paper_summaries/paper_summary_template.md
SUMMDIR=$(dirname ${TEMPLATE})/site/summaries
PAPERDIR=~/Papers/paper

# Other variables that don't change very often
CITEKEY_REGEX=[:alnum:]\+:[0-9]\{4\}
OPEN=mimeo

# Figure out if a paper or citekey was supplied
input=$1
if [ ${input: -4} == ".pdf" ]; then
  paper=${input}
  bn=$(basename -s .pdf $input)
  citekey=${bn##*-}
  citekey=`echo $citekey | sed s/_/:/`
else # assume this is a citekey
  citekey=$input
  paperkey=${input/:/_}
  paper=`ls ${PAPERDIR}/*${paperkey}.pdf | head -1`
fi

echo $paper
echo $citekey

# make sure the paper exists and the citekey is valid
#FIXME: too permissive it seems
if [[ ! $citekey =~ ${CITEKEYREGEX} ]]; then
  # FIXME: needs to echo to stderr
  echo invalid citekey: ${citekey}
  exit 1
fi
# make sure the file exists
if [ ! -f "$paper" ]; then
  echo paper ${paper} not found
  exit 2
fi

summfile=${SUMMDIR}/${citekey/:/_}.md
# copy the template file if needed
# TODO: fill this in with info from zotero
if [ ! -f "$summfile" ]; then
  cp ${TEMPLATE} ${summfile}
fi

# open the pdf and the summary document
mimeo ${paper}
vim ${summfile}

