#!/bin/sh

MAILDIR=~/.mail
GMAILACCTS="personal swansea sfu"

echo ---------- send pending messages --------------
msmtp-queue -r

echo ----------- moving tags to folders ------------
notmuch-imap-tag-mover

echo ---------------- email sync -------------------
for gm in ${GMAILACCTS};
do
  echo syncing "${gm}"
  (cd "${MAILDIR}/${gm}" && gmi sync)
done
mbsync -a

echo ----------------- notmuch ---------------------
notmuch new

echo -----------------  tags   ---------------------
notmuch-tag 

echo "done"

