#!/bin/sh

MAILDIR=~/.mail
GMAILACCTS="personal work sfu"

echo ---------- send pending messages --------------
msmtp-queue -r

echo ---------------- email sync -------------------
for gm in ${GMAILACCTS};
do
  echo syncing ${gm}
  (cd ${MAILDIR}/${gm} && gmi sync)
done
mbsync -a

echo ----------------- notmuch ---------------------
notmuch new

echo -----------------  tags   ---------------------
afew -v --tag --new

echo done

