#!/bin/sh

MAILDIR=~/.mail
GMAILACCTS="personal swansea sfu"

echo ---------- send pending messages --------------
msmtp-queue -r

echo ----------- moving tags to folders ------------
afew -m
archive_mails vrvis

echo ---------------- email sync -------------------
for gm in ${GMAILACCTS};
do
  echo syncing ${gm}
  (cd ${MAILDIR}/${gm} && gmi sync)
done
mbsync -a

echo ----------------- notmuch ---------------------
notmuch new

echo -----------------  tags   ---------------------
afew --tag --new

echo done

