#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir(bundles_dir) unless File.exist? bundles_dir
FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

url = "https://github.com/gmarik/vundle.git"
dir = "vundle"
`git clone #{url} #{dir}`

