#!/usr/bin/env ruby

# orig version from http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [ 
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/tristen/vim-sparkup.git",
  "git://github.com/vim-scripts/LustyJuggler.git",
  "git://github.com/thinca/vim-localrc.git",
  "git://github.com/jcf/vim-latex.git",
  "git://github.com/vim-scripts/Processing.git",
  "git://github.com/rosstimson/scala-vim-support.git",
  "git://github.com/vim-scripts/Vim-R-plugin.git",
  "git@github.com:torsneyt/snipmate-snippets.git",
  "git@github.com:torsneyt/vim-multimarkdown.git",
]

vim_org_scripts = [
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir(bundles_dir) unless File.exist? bundles_dir
FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  # only clear out git for stuff that's not mine
  FileUtils.rm_rf(File.join(dir, ".git")) unless url.include? 'torsneyt'
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
