#!/usr/bin/env bash

# based on https://notmuchmail.org/pipermail/notmuch/2019/028956.html

MAILDIR=$HOME/.mail

# Move a message file while removing its UID-part
function safeMove { s=${1##*/}; s=${s%%,*}; mv -f $1 $2/$s; }

if [ -z "$1" ]; then
  echo please provide a subdirectory to work with
  exit 1
fi

subdir=$1
proc_maildir=${MAILDIR}/${1}

folderquery="NOT folder:${subdir}/Archive AND folder:/${subdir}.*/"
untaggedquery="$(notmuch search --output=tags \* | sed 's/^/not tag:/;2~1s/^/and /')"
archivequery="${folderquery} AND ${untaggedquery}"

updatect=$(notmuch count ${archivequery})

# actually do the updating
# only need to update if any messages were moved
if [ ${updatect} -gt 0 ]; then
  echo Moving ${updatect} emails to ${subdir} archive
  for email in $(notmuch search --output=files ${archivequery}); do
    safeMove $email ${proc_maildir}/Archive/cur
  done

  notmuch new
else
  echo No messages to archive
fi

