#!/usr/bin/env bash

today=`date -I`

revfile=~/Sync/Notes/weekly_review_${today}.md 

# write the template file
cat << EOF > ${revfile}
---
title: $today weekly update
tags: #update
related: 
...

# Wins



# Lessons learned



# Things I'm greatful for



# Plans for next week



EOF

vim ${revfile}

