" 100% pure vim
set nocompatible
filetype off
set modeline " make sure per-file vim configs work

filetype plugin indent on " required

" appearance
set guifont=Anonymice\ Nerd\ Font\ 11
set termguicolors " enable true color support
colorscheme nord
set noshowmode
set cursorline " color current line
syntax on " syntax highlighting
" set the gutter color
" TODO: look into matchadd though to only highlight extended lines
execute "set colorcolumn=" . join(range(79,335), ',') 

" keep backup files and stuff outside of the working dir
set backupdir=/var/tmp/
set directory=/var/tmp/

" disable the f1 help key
map <F1> <Nop>

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set wrap linebreak nolist " softwrap lines
set autoindent

" show numbers in margin
set number

" tablular
vmap a= :Tabularize /=<CR>
vmap a; :Tabularize /::<CR>
vmap a- :Tabularize /-><CR>

" need a faster update time
set updatetime=100

" commands to edit and reload config
" things are weird because 
nnoremap <leader>ev :e $HOME/.config/nvim/scratch.vim<CR>
nnoremap <leader>sv :so $MYVIMRC<CR>

" make the Y command consistent with C and D
nnoremap Y y$

" quick clipboard commands especially since "+y is hard to type correctly :)
vmap <leader>y "+y
vmap <leader>d "+d
vmap <leader>p "+p

