#! /usr/bin/env bash

PROJ_DIRS=(~/projects ~/raicoon)

selected=$(find "${PROJ_DIRS[@]}" -type d -execdir test -e "{}/.git" \; -print | fzf)

# if we don't select everything just quit
if [ -z "$selected" ]; then
  exit 0
fi

tat "$selected"

