#! /usr/bin/env bash

# Let the user choose what screen
chosen=$(printf "window\\narea" | dmenu -i -p "Screenshot:") &&
  case "$chosen" in
    "window")
      shutter -a
      ;;
    "area")
      shutter -s
      ;;
  esac

