#!/bin/sh


session_name=Tasks

not_in_tmux() {
  [ -z "$TMUX" ]
}

session_exists() {
  tmux has-session -t "=$session_name"
}

create_detached_session() {
  (TMUX='' tmux new-session -Ad -s "$session_name")

  # create layout
  tmux split-window -v -l 4 -c ~/
  tmux select-pane -t 0
  tmux split-window -h -p 50 -c ~/
  tmux select-pane -t 0
  tmux split-window -v -p 50 -c ~/
  tmux select-pane -t 2
  tmux split-window -v -l 13 -c ~/

  # Send commands to the created panes
  tmux select-pane -t 0
  tmux send-keys 'while true; do; clear; task next limit:10; sleep 5; done' Enter
  tmux select-pane -t 1
  tmux send-keys 'while true; do; clear; task today; sleep 5; done' Enter
  tmux select-pane -t 2
  tmux send-keys 'while true; do; clear; task week; sleep 30; done' Enter
  tmux select-pane -t 3
  tmux send-keys 'while true; do; clear; task calendar; sleep 30; done' Enter

  tmux select-pane -t 4
}

create_if_needed_and_attach() {
  if ! session_exists; then
    create_detached_session
  fi
  if not_in_tmux; then
    tmux attach-session -t "$session_name"
  else
    tmux switch-client -t "$session_name"
  fi
}

create_if_needed_and_attach


