#!/bin/sh

MAILDIR=~/.mail
GMAILACCTS="personal work"

echo ---------------- email sync -------------------
for gm in ${GMAILACCTS};
do
  echo syncing ${gm}
  (cd ${MAILDIR}/${gm} && gmi sync)
done

echo ----------------- notmuch ---------------------
notmuch new

echo -----------------  tags   ---------------------
afew -v --tag --new

echo done

