#!/bin/sh

MAILDIR=~/.mail
GMAILACCTS="personal work sfu"

echo ---------- send pending messages --------------
msmtp-queue -r

#echo ------------ sync work sentmail ---------------
#mbsync sync-work-sent && rm ~/.mail/work/sent/cur/*

echo ---------------- email sync -------------------
for gm in ${GMAILACCTS};
do
  echo syncing ${gm}
  (cd ${MAILDIR}/${gm} && gmi sync)
done

echo ----------------- notmuch ---------------------
notmuch new

echo -----------------  tags   ---------------------
afew -v --tag --new

echo done

