#!/usr/bin/env bash

NEW_TAG=""

# parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--new)
      NEW_TAG="tag:new and"
      shift # skip arg
      ;;
    #-*|--*)
      #>&2 echo "Unknown option $1"
      #exit 1
      #;;
  esac
done

echo "Updating tags for mail"

# make sure the notmuch db is current
notmuch new

# Tags to just remove
echo "removing extraneous tags"
notmuch tag -important -- "${NEW_TAG}" tag:important
notmuch tag --remove-all +trash -- "${NEW_TAG}" tag:trash
notmuch tag --remove-all +spam  -- "${NEW_TAG}" tag:spam

# Mark all email from myself
echo "tagging sent mail"
notmuch tag +sent -new -- "${NEW_TAG}" from:"$(notmuch config get user.primary_email)" and not tag:sent
for addr in $(notmuch config get user.other_email); do
  notmuch tag +sent -new -- "${NEW_TAG}" from:"${addr}" and not tag:sent
done

# remove unread from sent mails (hopefully I read these before sending)
notmuch tag -unread -- "${NEW_TAG}" tag:sent

# Skip spam and trash
notmuch tag -new -- "${NEW_TAG}" tag:spam 
notmuch tag -new -- "${NEW_TAG}" tag:trash 

# TODO: tag threads: https://notmuchmail.org/faq/
#THREAD_TAGS="muted"
#for tag in "$THREAD_TAGS"; do
  #notmuch tag +$tag $(notmuch search --output=threads tag:$tag)
#done

# any other new emails fall through to inbox
echo "Unmark remaining mails to inbox"
notmuch tag -new -- tag:new

echo "Done"

