#!/usr/bin/env sh

NEW_TAG=""

# parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    -n|--new)
      NEW_TAG="tag:new and"
      shift # skip arg
      ;;
    -*|--*)
      >&2 echo "Unknown option $1"
      exit 1
      ;;
  esac
done

# don't assign tags for mails in these imap folders
declare -a NOTAG_FOLDERS=(Archive Junk) 

echo "=Updating tags for mail="

# make sure the notmuch db is current
notmuch new

# Tags to just remove
echo "removing extraneous tags"
notmuch tag -important -- ${NEW_TAG} tag:important

# Mark all email from myself
echo "tagging sent mail"
notmuch tag +sent -- from:$(notmuch config get user.primary_email) and not tag:sent
for addr in `notmuch config get user.other_email`; do
  notmuch tag +sent -new -- ${NEW_TAG} from:${addr} and not tag:sent
done

# remove unread from sent mails (hopefully I read these before sending)
notmuch tag -unread -- ${NEW_TAG} tag:sent

# emails in a folder should get the lowercase folder name as a tag
# this is special for imap accounts
# also remove the new tag so already filed messages don't end up in the inbox
echo "Tag with IMAP folders"
declare -A NOTAG_MAP=() # convert to associative array for membership checking
for k in "${NOTAG_FOLDERS[@]}"; do NOTAG_MAP[$k]=1; done
for folder in `notmuch search --output=files folder:'/vrvis.*/' | grep '/.mail/vrvis/' | sed 's#.*/vrvis/\([^/]*\)/.*#\1#' | sort -u`; do
  if [ -z "${NOTAG_MAP[$folder]}" ]; then
    tag="${folder,,}"
    notmuch tag +${tag} -new -- ${NEW_TAG} folder:vrvis/${folder} and not tag:${tag}
  fi
done
# vrvis Junk folder is where spam lives
notmuch tag +spam -new -- ${NEW_TAG} folder:vrvis/Junk and not tag:spam

# Skip spam and trash
notmuch tag -new -- ${NEW_TAG} tag:spam 
notmuch tag -new -- ${NEW_TAG} tag:trash 

# remove new from imap archive messages so they don't end up in the inbox
# they don't get tags to stay consistent with gmail
echo "Leaving archive mails"
notmuch tag -new -- folder:vrvis/Archive and tag:new

# emails can't be in inbox and archive
echo "Remaining mails to inbox"
notmuch tag -inbox -- ${NEW_TAG} folder:vrvis/Archive and tag:inbox

# TODO: tag threads: https://notmuchmail.org/faq/
#THREAD_TAGS="muted"
#for tag in "$THREAD_TAGS"; do
  #notmuch tag +$tag $(notmuch search --output=threads tag:$tag)
#done

# any other new emails fall through to inbox
notmuch tag +inbox -new -- tag:new and not tag:inbox

echo "=Done="

