#! /usr/bin/env bash

SSHPORT=2200

# ARGUMENT PASSING start
# ======================
# source: https://stackoverflow.com/questions/5474732/how-can-i-add-a-help-method-to-a-shell-script
usage() {
        echo "$(basename "$0") [-h] TARGET_HOST TARGET_PORT [LOCAL_PORT] -- create an ssh tunnel to a specific port

where:
    -h  show this help text"
}

if [ "$1" == "-h" ]; then
        usage
        exit
fi

if [ -z "$1" ] || [ -z "$2" ]; then
        usage
        exit 1
fi

TARGET_HOST=$1
TARGET_PORT=$2
LOCAL_PORT=$TARGET_PORT

if [ -n "$3" ]; then
        LOCAL_PORT=$3
fi
# ARGUMENT PASSING end
# ====================

USER=$(whoami)

echo "Connecting as user $USER and forwarding $TARGET_HOST:$TARGET_PORT to localhost:$LOCAL_PORT ..."
ssh -i ~/keys/id_ed25519_raicoon -Cp${SSHPORT} -NL "$LOCAL_PORT":"$TARGET_HOST":"$TARGET_PORT" "$USER"@vpn.gt-d.com
